title: UFSIT
subtitle: UF's Security Infosec Team!
description: >- # this means to ignore newlines until "baseurl:"
  Official homepage and blog for UFSIT

url: "ufsit.club" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

urls:
    - text: About
      url: /about
    - text: Writeups
      url: /blog
    - text: Contact
      url : /contact
    - text: Join the Slack!
      external_url: https://app.slack.com/client/T08DLLF9N/C09KW9MP1
      external_site: Slack
    - text: CTF Discord
      external_url: https://discord.gg/YgDedaz
      external_site: Discord

# Edit these details

author_logo: ufsitlogo.png
author: UFSIT
author_bio: bleh
author_email: "president@ufsit.org"
author_location: University of Florida
author_website_url: "ufsit.club"

# social links
twitter_username: ufsit
github_username:  ufsit
facebook_username: ufsit

#for comments using disqus
disqus_shortname: user

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
